pull_request_rules:
  - name: Automatic merge Dependabot PRs on CI success
    conditions:
      - base=main
      - author=dependabot[bot]
      - status-success=test
      - "#review-requested=0"
      - -dependabot-dependency-name~=org.scala-lang
    actions:
      merge:
        method: squash
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - base = main
      - label = merge
      - status-success = test
      - "#review-requested=0"
    actions:
      merge:
        method: squash
